-- Disable RLS on all tables to allow custom auth flow
-- Users & Core
ALTER TABLE IF EXISTS public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.residents DISABLE ROW LEVEL SECURITY;

-- Medical & Logs
ALTER TABLE IF EXISTS public.vital_signs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.care_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.nutrition_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.elimination_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.medication_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.medication_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.nursing_notes DISABLE ROW LEVEL SECURITY;

-- Education / Other Schema
ALTER TABLE IF EXISTS public.classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.class_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.topics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.stream_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.assignment_students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.assignment_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quizzes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quiz_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quiz_students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quiz_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.material_students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.grades DISABLE ROW LEVEL SECURITY;

-- Notify schema reload
NOTIFY pgrst, 'reload schema';
